import type { QuizSet, Question, AppAssignment } from "@/types";

export const seedQuizSets: QuizSet[] = [
  {
    id: "quiz-1",
    name: "Math Quickies",
    topic: "Mathematics",
    difficulty: "Easy",
    notes: "Basic arithmetic and mental math",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "quiz-2",
    name: "Vocabulary Builder",
    topic: "Language",
    difficulty: "Medium",
    notes: "Expand your vocabulary",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const seedQuestions: Question[] = [
  {
    id: "q-1",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 7 × 8?",
    choices: ["54", "56", "64", "48"],
    correctAnswer: "56",
    explanation: "7 × 8 = 56. Remember: 7 × 8 = 56 (five, six, seven, eight!)",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-2",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 15% of 200?",
    choices: ["25", "30", "35", "40"],
    correctAnswer: "30",
    explanation: "15% of 200 = 0.15 × 200 = 30",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-3",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is the square root of 144?",
    choices: ["10", "11", "12", "13"],
    correctAnswer: "12",
    explanation: "√144 = 12, because 12 × 12 = 144",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-4",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 9 + 6 × 2?",
    choices: ["30", "21", "27", "24"],
    correctAnswer: "21",
    explanation: "Order of operations: 6 × 2 = 12, then 9 + 12 = 21",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-5",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 100 ÷ 4?",
    choices: ["20", "25", "30", "35"],
    correctAnswer: "25",
    explanation: "100 ÷ 4 = 25",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-6",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 3³ (3 cubed)?",
    choices: ["6", "9", "27", "81"],
    correctAnswer: "27",
    explanation: "3³ = 3 × 3 × 3 = 27",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-7",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 12 × 12?",
    choices: ["124", "144", "154", "164"],
    correctAnswer: "144",
    explanation: "12 × 12 = 144",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-8",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 50% of 80?",
    choices: ["30", "35", "40", "45"],
    correctAnswer: "40",
    explanation: "50% of 80 = 0.5 × 80 = 40",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-9",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 18 ÷ 3?",
    choices: ["4", "5", "6", "7"],
    correctAnswer: "6",
    explanation: "18 ÷ 3 = 6",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-10",
    quizSetId: "quiz-1",
    type: "mcq",
    prompt: "What is 2⁴ (2 to the power of 4)?",
    choices: ["8", "12", "16", "20"],
    correctAnswer: "16",
    explanation: "2⁴ = 2 × 2 × 2 × 2 = 16",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-11",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'to make something less severe'?",
    acceptableAnswers: ["mitigate", "alleviate", "ease"],
    explanation: "Mitigate means to make less severe, serious, or painful.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-12",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'existing everywhere at the same time'?",
    acceptableAnswers: ["ubiquitous", "omnipresent"],
    explanation: "Ubiquitous means present, appearing, or found everywhere.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-13",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'a person who attacks cherished beliefs'?",
    acceptableAnswers: ["iconoclast"],
    explanation: "An iconoclast is someone who challenges or overturns traditional beliefs.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-14",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'brief and to the point'?",
    acceptableAnswers: ["concise", "succinct", "terse"],
    explanation: "Concise means giving a lot of information clearly in few words.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-15",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'to spread negative information about someone'?",
    acceptableAnswers: ["defame", "slander", "libel"],
    explanation: "Defame means to damage someone's reputation by false statements.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-16",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'using few words'?",
    acceptableAnswers: ["laconic", "terse", "concise"],
    explanation: "Laconic means using very few words to express much.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-17",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'showing great attention to detail'?",
    acceptableAnswers: ["meticulous", "thorough", "careful"],
    explanation: "Meticulous means showing great attention to detail; very careful and precise.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-18",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'to make worse or more severe'?",
    acceptableAnswers: ["exacerbate", "aggravate", "worsen"],
    explanation: "Exacerbate means to make a problem, bad situation, or negative feeling worse.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-19",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'generous or forgiving'?",
    acceptableAnswers: ["magnanimous", "benevolent", "generous"],
    explanation: "Magnanimous means generous or forgiving, especially toward a rival or less powerful person.",
    timesSeen: 0,
    timesCorrect: 0,
  },
  {
    id: "q-20",
    quizSetId: "quiz-2",
    type: "short_answer",
    prompt: "What word means 'a beginner or novice'?",
    acceptableAnswers: ["neophyte", "novice", "beginner"],
    explanation: "A neophyte is a person who is new to a subject, skill, or belief.",
    timesSeen: 0,
    timesCorrect: 0,
  },
];

export const seedAppAssignments: AppAssignment[] = [
  {
    id: "app-1",
    appName: "Instagram",
    quizSetId: "quiz-1",
    schemeOrStoreURL: "instagram://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
  {
    id: "app-2",
    appName: "TikTok",
    quizSetId: "quiz-2",
    schemeOrStoreURL: "tiktok://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
  {
    id: "app-3",
    appName: "YouTube",
    quizSetId: "quiz-1",
    schemeOrStoreURL: "youtube://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
  {
    id: "app-4",
    appName: "X",
    quizSetId: "quiz-2",
    schemeOrStoreURL: "twitter://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
  {
    id: "app-5",
    appName: "Reddit",
    quizSetId: "quiz-1",
    schemeOrStoreURL: "reddit://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
  {
    id: "app-6",
    appName: "Snapchat",
    quizSetId: "quiz-2",
    schemeOrStoreURL: "snapchat://",
    randomize: true,
    requireStreak: 1,
    cooldownSeconds: 0,
    enabled: false,
  },
];
